controller_app/config/routes.rb
Rails.application.routes.draw do

  resources :bookings

  root 'bookings#index'

end

controller_app/app/models/booking.rb
class Booking < ActiveRecord::Base
end

controller_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

controller_app/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def index
		@bookings = Booking.all
	end

	def show
		@booking = Booking.find(params[:id])
	end

	def new
		@booking = Booking.new
	end

	def create
		@booking = Booking.new(booking_params)

		if @booking.save
			redirect_to @booking
		else
			render "new"
		end
	end

	def edit
		@booking = Booking.find(params[:id])
	end

	def update
		@booking = Booking.find(params[:id])

		if @booking.update(booking_params)
			redirect_to @booking
		else
			render 'edit'
		end
	end

	def destroy
		@booking = Booking.find(params[:id])
		@booking.destroy

		redirect_to bookings_path
	end

private
	def booking_params
		params.require(:booking).permit(:student, :question, :additional_comments)
	end
end

controller_app/app/helpers/application_helper.rb
module ApplicationHelper
end

controller_app/app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student %><br>
    <%= f.text_field :student %>
  </div>
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :additional_comments %><br>
    <%= f.text_area :additional_comments %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

controller_app/app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>

<%= render "form" %>

controller_app/app/views/bookings/index.html.erb
<table>
  <thead>
    <tr>
      <th><h2>TA Queue</h2></th>
    </tr>
    <tr>
      <th>Student</th>
      <th>Question</th>
      <th>Additional comments</th>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.student %></td>
        <td><%= booking.question %></td>
        <td><%= booking.additional_comments %></td>
        <td><%= link_to 'Show', booking_path(booking) %></h2></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Question answered', booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Booking', new_booking_path %></p>

controller_app/app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

controller_app/app/views/bookings/show.html.erb
<h1>TA Booking</h1>

<p>
  <strong>Student:</strong>
  <%= @booking.student %>
</p>

<p>
  <strong>Question:</strong>
  <%= @booking.question %>
</p>

<p>
  <strong>Additional Comments:</strong>
  <%= @booking.additional_comments %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

controller_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Week2DemoNoController</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>