model_app/config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  root 'welcome#index'

end

model_app/app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
end

model_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

model_app/app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
	def index
		@pokemons = Pokemon.all
	end

	def show
		@pokemon = Pokemon.find(params[:id])
	end

	def new
		@pokemon = Pokemon.new
	end

	def edit
		@pokemon = Pokemon.find(params[:id])
	end


	def create
		@pokemon = Pokemon.new(pokemon_params)

		if @pokemon.save
			redirect_to @pokemon
		else
			render 'new'
		end
	end

	def update
	  @pokemon = Pokemon.find(params[:id])
	 
	  if @pokemon.update(pokemon_params)
	    redirect_to @pokemon
	  else
	    render 'edit'
		end
	end

	def destroy
		@pokemon = Pokemon.find(params[:id])
		@pokemon.destroy

		redirect_to pokemons_path
	end

	private
		def pokemon_params
			params.require(:pokemon).permit(:name, :element_text, :power_level)
		end
end

model_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

model_app/app/helpers/application_helper.rb
module ApplicationHelper
end

model_app/app/helpers/pokemon_helper.rb
module PokemonHelper
end

model_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

model_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Animal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

model_app/app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>
 
<%= form_for :pokemon, url: pokemon_path(@pokemon), method: :patch do |f| %>
 
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pokemon.errors.count, "error") %> prohibited
        this pokemon from being saved:
      </h2>
      <ul>
        <% @pokemon.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :element_text %><br>
    <%= f.text_area :element_text %>
  </p>
  
  <p>
    <%= f.label :power_level %><br>
    <%= f.text_area :power_level %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', pokemons_path %>

model_app/app/views/pokemons/index.html.erb
<h1>Listing pokemons</h1>
<%= link_to 'New Pokemon', new_pokemon_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Element</th>
    <th>Power Level</th>
  </tr>
 
  <% @pokemons.each do |pokemon| %>
    <tr>
      <td><%= pokemon.name %></td>
      <td><%= pokemon.element_text %></td>
      <td><%= pokemon.power_level %></td>
      <td><%= link_to 'Show', pokemon_path(pokemon) %></td>
      <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
      <td><%= link_to 'Destroy', pokemon_path(pokemon),
              method: :delete,
              data: { confirm: 'Are you sure you want to destroy this pokemon?'} %></td>
    </tr>
  <% end %>
</table>

model_app/app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= form_for :pokemon, url: pokemons_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :element_text %><br>
    <%= f.text_area :element_text %>
  </p>

  <p>
    <%= f.label :power_level %><br>
    <%= f.text_area :power_level %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', pokemons_path %>

model_app/app/views/pokemons/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @pokemon.name %>
</p>
 
<p>
  <strong>Type:</strong>
  <%= @pokemon.element_text %>
</p>
 
<p>
  <strong>Power Level:</strong>
  <%= @pokemon.power_level %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>

model_app/app/views/welcome/index.html.erb
<h1>Hello Session 3!</h1>
<%= link_to 'My Pokemon', controller: 'pokemons' %>
<%= link_to 'New Pokemon', new_pokemon_path %>