views_app/config/routes.rb
Rails.application.routes.draw do

  root 'rusks#index'

  resources :rusks

end

views_app/app/models/rusk.rb
class Rusk < ActiveRecord::Base
	validates :base, :extras, :dippable, presence: true
	validates :crunch_factor, numericality: { only_integer: true, greater_than: 0}
end

views_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

views_app/app/controllers/rusks_controller.rb
class RusksController < ApplicationController
def index
		@rusks = Rusk.all
	end

	def show
		@rusk = Rusk.find params[:id]
	end

	def new
		@rusk = Rusk.new
	end

	def edit
		@rusk = Rusk.find params[:id]
	end
	
	def create
		@rusk = Rusk.new(rusk_params)

		if @rusk.save
			redirect_to @rusk
		else
			render 'new'
		end
	end

	def update
		@rusk = Rusk.find params[:id]

		if @rusk.update(rusk_params)
			redirect_to @rusk
		else
			render 'edit'
		end
	end

	def destroy
		@rusk = Rusk.find params[:id]
		@rusk.destroy

		redirect_to rusks_path
	end

	private

	def rusk_params
		params.require(:rusk).permit(:name, :base, :extras, :dippable, :crunch_factor)
	end

end

views_app/app/helpers/application_helper.rb
module ApplicationHelper
end

views_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RuskMaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

views_app/app/views/rusks/_form.html.erb
<%= form_for @rusk do |f| %>
	<% if @rusk.errors.any? %>
		<div id="error explanation">
			<h2> <%= pluralize(@rusk.errors.count, "error") %>
			prohibitied this place from being saved: </h2>

			<ul>
				<% @rusk.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<%end %>
			</ul>
	<div>
	<%end%>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div>
	<%= f.label :base %>
	<%= f.text_field :base %>
	</div>

	<div>
	<%= f.label :extras %>
	<%= f.text_field :extras %>
	</div>

	<div>
	<%= f.label :dippable %>
	<%= f.check_box :dippable %>
	</div>

	<div>
	<%= f.label :crunch_factor %>
	<%= f.text_field :crunch_factor %>
	</div>

	<%= f.submit %>
<% end %>

views_app/app/views/rusks/edit.html.erb
<h1>Edit a Rusk</h1>

<%= render 'form' %>

<%= link_to 'All Rusks', rusks_path %>

views_app/app/views/rusks/index.html.erb
<h1>All the Rusks</h1>

<h3>Make a New Rusk!</h3>
	<p><%= link_to 'New Rusk', new_rusk_path %></p>
<ul>
	<% @rusks.each do |rusk| %>
		<li><%=link_to rusk.name, rusk_path(rusk)%> | 
		<%= link_to 'Edit', edit_rusk_path(rusk) %> | 
		<%= link_to 'Destroy', rusk_path(rusk),
			method: :delete,
			data: { confirm: 'Are you sure you want destroy this delicious rusk?' } %></li>
	<% end %>
</ul>

views_app/app/views/rusks/new.html.erb
<h1>Make a New Rusk</h1>

<%= render 'form' %>

<%= link_to 'All Rusks', rusks_path %>

views_app/app/views/rusks/show.html.erb
<h1><%= @rusk.name %></h1>

<h3>Base:</h3>
	<p><%= @rusk.base%></p>
<h3>Extras:</h3>
	<p><%= @rusk.extras%></p>
<h3>Dippable:</h3>
	<p><%= @rusk.dippable%></p>
<h3>Crunch Factor:</h3>
	<p><%= @rusk.crunch_factor%></p>

<%= link_to 'All Rusks', rusks_path %>